CREATE TABLE IF NOT EXISTS school
(
    id   BIGINT       NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

ALTER TABLE person
    ADD COLUMN school_id BIGINT REFERENCES school ON DELETE SET NULL;